CREATE DATABASE sensores;
USE sensores;
CREATE TABLE cadastro (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR (80),
    dtNasc DATE,
    nivelAcesso VARCHAR (20),
    email VARCHAR (60)NOT NULL,
    login VARCHAR (40) NOT NULL,
    senha VARCHAR (12) NOT NULL,
    telefone INT,
    dtCadastro DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE deteccao (
	id INT PRIMARY KEY AUTO_INCREMENT,
    idSensor VARCHAR (40),
    dtDeteccao DATETIME DEFAULT CURRENT_TIMESTAMP
);